
package peli.logic;


public enum TileType {

    PLAINS, HILLS, MOUNTAINS, FOREST, MINENEUTRAL, FARMNEUTRAL, OUTPOSTNEUTRAL, REDHQ, ROADVERTICAL, ROADUPRIGHTDOWN, ROADHORIZONTAL, ROADDOWNTOLEFT, ROADUPLEFTDOWN, ROADDOWNTORIGHT, ROADUPTOLEFT, ROADUPTORIGHT, BLUEHQ 
}
